# Generated by Django 4.0.1 on 2022-04-20 20:01

from django.db import migrations
import django_resized.forms
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[400, 400], upload_to=main_app.models.upload_gallery_image),
        ),
    ]
